<!DOCTYPE html>
<html lang="en-US">
    <head>
        <meta charset="utf-8"> 
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="author" content="akshar" />
        <meta name="copyright" content="akshar" />

        <meta property="og:type" content="article" />
        <meta name="twitter:card" content="summary">

<meta name="keywords" content="celery, markdown, " />

<meta property="og:title" content="Retrying celery failed tasks "/>
<meta property="og:url" content="/retrying-celery-failed-tasks.html" />
<meta property="og:description" content="I assume you have a basic understanding of celery. If you want to learn about basics of celery, you can check our last blog. ### Use case In one of my projects, I work with Twitter api. I need to fetch a user&#39;s tweets. Twitter provides an api endpoint for fetching user&#39;s tweets. Fetching of tweets involve network calls and so should happen in background, so we fetch the tweets using a celery task. So I have a celery task which makes one api call to Twitter. If I am able to fetch the tweets I consider the" />
<meta property="og:site_name" content="agiliq_blog" />
<meta property="og:article:author" content="akshar" />
<meta property="og:article:published_time" content="2015-08-03T00:23:19+05:30" />
<meta property="" content="2015-08-03T10:53:19+05:30" />
<meta name="twitter:title" content="Retrying celery failed tasks ">
<meta name="twitter:description" content="I assume you have a basic understanding of celery. If you want to learn about basics of celery, you can check our last blog. ### Use case In one of my projects, I work with Twitter api. I need to fetch a user&#39;s tweets. Twitter provides an api endpoint for fetching user&#39;s tweets. Fetching of tweets involve network calls and so should happen in background, so we fetch the tweets using a celery task. So I have a celery task which makes one api call to Twitter. If I am able to fetch the tweets I consider the">

        <title>Retrying celery failed tasks  Â· agiliq_blog
</title>
        <link href="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/css/bootstrap-combined.min.css" rel="stylesheet">
        <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.1/css/font-awesome.css" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="/theme/css/pygments.css" media="screen">
        <link rel="stylesheet" type="text/css" href="/theme/tipuesearch/tipuesearch.css" media="screen">
        <link rel="stylesheet" type="text/css" href="/theme/css/elegant.css" media="screen">
        <link rel="stylesheet" type="text/css" href="/theme/css/custom.css" media="screen">
    </head>
    <body>
        <div id="content-sans-footer">
        <div class="navbar navbar-static-top">
            <div class="navbar-inner">
                <div class="container-fluid">
                    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </a>
                    <a class="brand" href="/"><span class=site-name>agiliq_blog</span></a>
                    <div class="nav-collapse collapse">
                        <ul class="nav pull-right top-menu">
                            <li ><a href="">Home</a></li>
                            <li ><a href="/categories.html">Categories</a></li>
                            <li ><a href="/tags.html">Tags</a></li>
                            <li ><a href="/archives.html">Archives</a></li>
                            <li><form class="navbar-search" action="/search.html" onsubmit="return validateForm(this.elements['q'].value);"> <input type="text" class="search-query" placeholder="Search" name="q" id="tipue_search_input"></form></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <div class="container-fluid">
            <div class="row-fluid">
                <div class="span1"></div>
                <div class="span10">
<article>
<div class="row-fluid">
    <header class="page-header span10 offset2">
    <h1><a href="/retrying-celery-failed-tasks.html"> Retrying celery failed tasks  </a></h1>
    </header>
</div>

<div class="row-fluid">
        <div class="span8 offset2 article-content">

            
            <p>I assume you have a basic understanding of celery. If you want to learn about basics of celery, you can check our <a href="http://agiliq.com/blog/2015/07/getting-started-with-celery-and-redis/" target="_blank">last blog</a>.</p>
<h3>Use case</h3>
<p>In one of my projects, I work with Twitter api. I need to fetch a user's tweets. Twitter provides an api endpoint for fetching user's tweets. Fetching of tweets involve network calls and so should happen in background, so we fetch the tweets using a celery task. So I have a celery task which makes one api call to Twitter. If I am able to fetch the tweets I consider the celery task was successful.</p>
<p>But Twitter rate limits this api endpoint and I can't hit this api endpoint indefinite number of times. Twitter allows maximum of 180 calls to this endpoint in a 15 minute window. Any call beyond 180 calls will start failing and Twitter will raise an exception instead of returning tweets. If Twitter raises exception instead of returning tweets, I consider that the celery task has failed.</p>
<p>Assuming a very active Twitter user signs up and we need 200 api calls to fetch all his tweets. So my celery tasks run 200 times. First 180 tasks would succeed but next 20 tasks would fail because of rate limiting.</p>
<p>I do not want to miss any tweet by a user, and so any failed task must be retried after 15 minutes. This is where celery retry functionality comes into picture.</p>
<h4>Pseudocode for my usecase</h4>
<div class="highlight"><pre><span></span>@app.task(bind=True)
def fetch_tweets(token_details):
    # token_details is user specific User token that needs to be passed to Twitter
    try:
        resp = make_twitter_call()  
        # Till 180 calls to Twitter, we will get `resp`
        # process result
    except TwitterException:
        # Till 180th call, this part will not be executed
        # 181th call onwards, Twitter will raise an error and this part of code will be executed
        # Retry fetch_tweets after 15 mins.
</pre></div>


<p>Before fixing this use case, let's play around with some basic examples.</p>
<h3>Basic example</h3>
<p>Create a file called add.py with following content</p>
<h6>add.py</h6>
<div class="highlight"><pre><span></span><span class="kn">from</span> <span class="nn">celery</span> <span class="kn">import</span> <span class="n">Celery</span>

<span class="n">app</span> <span class="o">=</span> <span class="n">Celery</span><span class="p">(</span><span class="s1">&#39;add&#39;</span><span class="p">,</span> <span class="n">broker</span><span class="o">=</span><span class="s1">&#39;redis://localhost:6379/0&#39;</span><span class="p">)</span>

<span class="nd">@app.task</span><span class="p">(</span><span class="n">bind</span><span class="o">=</span><span class="bp">True</span><span class="p">)</span>
<span class="k">def</span> <span class="nf">add</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">x</span><span class="p">,</span> <span class="n">y</span><span class="p">):</span>
    <span class="k">return</span> <span class="n">x</span> <span class="o">+</span> <span class="n">y</span>
</pre></div>


<p>Ensure task defined in this file is running properly by running the worker and trying to run the task from ipython shell.</p>
<h6>Worker terminal</h6>
<div class="highlight"><pre><span></span>celery worker -A add -l info
</pre></div>


<h6>Ipython</h6>
<div class="highlight"><pre><span></span><span class="kn">from</span> <span class="nn">add</span> <span class="kn">import</span> <span class="n">add</span>
<span class="n">add</span><span class="o">.</span><span class="n">delay</span><span class="p">(</span><span class="mi">3</span><span class="p">,</span> <span class="mi">4</span><span class="p">)</span>
</pre></div>


<p>After you do this, addition should happen and "7", i.e 3+4, should be printed on worker terminal.</p>
<h4>Explicity raising error</h4>
<p>Setting up Twitter access tokens etc will take effort and time, so instead of setting up Twitter, let's try to replicate a similar scenario where some calls to our task succeed and some calls to task fail.</p>
<p>Let's first replicate a failed task. A failed task means an error happening in the task. Raise an error in your task, and see how it behaves.</p>
<div class="highlight"><pre><span></span><span class="kn">from</span> <span class="nn">celery</span> <span class="kn">import</span> <span class="n">Celery</span>

<span class="n">app</span> <span class="o">=</span> <span class="n">Celery</span><span class="p">(</span><span class="s1">&#39;add&#39;</span><span class="p">,</span> <span class="n">broker</span><span class="o">=</span><span class="s1">&#39;redis://localhost:6379/0&#39;</span><span class="p">)</span>

<span class="nd">@app.task</span><span class="p">(</span><span class="n">bind</span><span class="o">=</span><span class="bp">True</span><span class="p">)</span>
<span class="k">def</span> <span class="nf">add</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">x</span><span class="p">,</span> <span class="n">y</span><span class="p">):</span>
    <span class="k">raise</span> <span class="ne">Exception</span><span class="p">()</span>
    <span class="k">return</span> <span class="n">x</span> <span class="o">+</span> <span class="n">y</span>
</pre></div>


<p>Restart celery worker</p>
<div class="highlight"><pre><span></span>celery worker -A add -l info
</pre></div>


<p>Run the task again</p>
<div class="highlight"><pre><span></span><span class="kn">from</span> <span class="nn">add</span> <span class="kn">import</span> <span class="n">add</span>
<span class="n">add</span><span class="o">.</span><span class="n">delay</span><span class="p">(</span><span class="mi">3</span><span class="p">,</span> <span class="mi">4</span><span class="p">)</span>
</pre></div>


<p>On celery terminal, you will see that an exception is raised.</p>
<div class="highlight"><pre><span></span>[2015-07-31 16:39:13,440: ERROR/MainProcess] Task add.add[fb067fbf-e79e-4fdd-b398-94da6be960e1] raised unexpected: Exception()
Traceback (most recent call last):
  File &quot;/Users/akshar/.virtualenvs/hack/lib/python2.7/site-packages/celery/app/trace.py&quot;, line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File &quot;/Users/akshar/.virtualenvs/hack/lib/python2.7/site-packages/celery/app/trace.py&quot;, line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File &quot;/Users/akshar/Play/Python/hack/add.py&quot;, line 7, in add
    raise Exception()
Exception
</pre></div>


<p>Suppose you want to retry the task after 2 seconds when it fails. Make the following code change</p>
<div class="highlight"><pre><span></span><span class="kn">from</span> <span class="nn">celery</span> <span class="kn">import</span> <span class="n">Celery</span>

<span class="n">app</span> <span class="o">=</span> <span class="n">Celery</span><span class="p">(</span><span class="s1">&#39;add&#39;</span><span class="p">,</span> <span class="n">broker</span><span class="o">=</span><span class="s1">&#39;redis://localhost:6379/0&#39;</span><span class="p">)</span>

<span class="nd">@app.task</span><span class="p">(</span><span class="n">bind</span><span class="o">=</span><span class="bp">True</span><span class="p">)</span>
<span class="k">def</span> <span class="nf">add</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">x</span><span class="p">,</span> <span class="n">y</span><span class="p">):</span>
    <span class="k">try</span><span class="p">:</span>
        <span class="k">raise</span> <span class="ne">Exception</span><span class="p">()</span>
    <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">retry</span><span class="p">(</span><span class="n">countdown</span><span class="o">=</span><span class="mi">2</span><span class="p">,</span> <span class="n">exc</span><span class="o">=</span><span class="n">e</span><span class="p">)</span>
    <span class="k">return</span> <span class="n">x</span> <span class="o">+</span> <span class="n">y</span>
</pre></div>


<p>Restart celery, run the task and check the output. Output would be</p>
<div class="highlight"><pre><span></span>2015-07-31 16:59:24,027: INFO/MainProcess] Received task: add.add[f9c6a487-9fd7-4bb2-8db6-2c58849809c7] eta:[2015-07-31 11:29:26.014576+00:00]
[2015-07-31 16:59:24,030: INFO/MainProcess] Task add.add[f9c6a487-9fd7-4bb2-8db6-2c58849809c7] retry: Retry in 2s: Exception()
[2015-07-31 16:59:26,075: INFO/MainProcess] Received task: add.add[f9c6a487-9fd7-4bb2-8db6-2c58849809c7] eta:[2015-07-31 11:29:28.065412+00:00]
[2015-07-31 16:59:26,076: INFO/MainProcess] Task add.add[f9c6a487-9fd7-4bb2-8db6-2c58849809c7] retry: Retry in 2s: Exception()
[2015-07-31 16:59:28,127: INFO/MainProcess] Received task: add.add[f9c6a487-9fd7-4bb2-8db6-2c58849809c7] eta:[2015-07-31 11:29:30.115907+00:00]
[2015-07-31 16:59:28,128: INFO/MainProcess] Task add.add[f9c6a487-9fd7-4bb2-8db6-2c58849809c7] retry: Retry in 2s: Exception()
[2015-07-31 16:59:30,771: ERROR/MainProcess] Task add.add[f9c6a487-9fd7-4bb2-8db6-2c58849809c7] raised unexpected: Exception()
Traceback (most recent call last):
  File &quot;/Users/akshar/.virtualenvs/hack/lib/python2.7/site-packages/celery/app/trace.py&quot;, line 240, in trace_task
  ...
  ....
  File &quot;/Users/akshar/Play/Python/hack/add.py&quot;, line 8, in add
    raise Exception()
Exception
</pre></div>


<h4>Explanation</h4>
<ul>
<li>Task ran for first time.</li>
<li>An error was raised which you caught.</li>
<li>We retried the task after 2 seconds in case of error.</li>
<li>Currently our task is written in such a way that every run of task raises error. So first retry of task also raised error.</li>
<li>Task was retried for 3 times, which is the celery default.</li>
<li>Third retry also raised an error, but instead of executing the code of "except" block, celery is smart to figure out that a task should only be retried 3 times and should not be retried forever.</li>
</ul>
<h4>Retry only once</h4>
<p>Suppose you only want to retry a failed task once instead of three which is the celery default.</p>
<p>Change self.retry line, so it looks like</p>
<div class="highlight"><pre><span></span>self.retry(countdown=2, exc=e, max_retries=1)
</pre></div>


<p>Restart celery and run the task, output would be</p>
<div class="highlight"><pre><span></span><span class="k">[2015-07-31 17:36:57,065: INFO/MainProcess] Received task: add.add[d1b099a4-026f-4bff-9bfd-8833a2b742e3]</span>
<span class="k">[2015-07-31 17:36:57,086: INFO/MainProcess] Received task: add.add[d1b099a4-026f-4bff-9bfd-8833a2b742e3] eta:[2015-07-31 12:06:59.076743+00:00]</span>
<span class="na">[2015-07-31 17:36:57,087: INFO/MainProcess] Task add.add[d1b099a4-026f-4bff-9bfd-8833a2b742e3] retry: Retry in 2s: Exception()</span>
<span class="na">[2015-07-31 17:37:00,968: ERROR/MainProcess] Task add.add[d1b099a4-026f-4bff-9bfd-8833a2b742e3] raised unexpected: Exception()</span>
<span class="na">Traceback (most recent call last):</span>
  <span class="na">File &quot;/Users/akshar/.virtualenvs/hack/lib/python2.7/site-packages/celery/app/trace.py&quot;, line 240, in trace_task</span>
  <span class="na">......</span>
  <span class="na">File &quot;/Users/akshar/Play/Python/hack/add.py&quot;, line 8, in add</span>
    <span class="na">raise Exception()</span>
<span class="na">Exception</span>
</pre></div>


<p>This time, the failed task was retried only once.</p>
<h3>Replicating exact Twitter scenario</h3>
<p>We want the task to succeed in some cases and fail in other cases. Modify your code, so it looks like:</p>
<div class="highlight"><pre><span></span><span class="kn">import</span> <span class="nn">random</span>

<span class="kn">from</span> <span class="nn">celery</span> <span class="kn">import</span> <span class="n">Celery</span>

<span class="n">app</span> <span class="o">=</span> <span class="n">Celery</span><span class="p">(</span><span class="s1">&#39;add&#39;</span><span class="p">,</span> <span class="n">broker</span><span class="o">=</span><span class="s1">&#39;redis://localhost:6379/0&#39;</span><span class="p">)</span>

<span class="nd">@app.task</span><span class="p">(</span><span class="n">bind</span><span class="o">=</span><span class="bp">True</span><span class="p">)</span>
<span class="k">def</span> <span class="nf">add</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">x</span><span class="p">,</span> <span class="n">y</span><span class="p">):</span>
    <span class="c1"># Get a random number between 1 and 10</span>
    <span class="n">num</span> <span class="o">=</span> <span class="n">random</span><span class="o">.</span><span class="n">randint</span><span class="p">(</span><span class="mi">1</span><span class="p">,</span> <span class="mi">10</span><span class="p">)</span>
    <span class="k">print</span> <span class="n">num</span> <span class="c1"># To help properly understand output</span>
    <span class="k">try</span><span class="p">:</span>
        <span class="c1"># If number is odd, fail the task</span>
        <span class="k">if</span> <span class="n">num</span> <span class="o">%</span> <span class="mi">2</span><span class="p">:</span>
            <span class="k">raise</span> <span class="ne">Exception</span><span class="p">()</span>
        <span class="c1"># If number is even, succeed the task</span>
        <span class="k">else</span><span class="p">:</span>
            <span class="k">return</span> <span class="n">x</span> <span class="o">+</span> <span class="n">y</span>
    <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">retry</span><span class="p">(</span><span class="n">countdown</span><span class="o">=</span><span class="mi">2</span><span class="p">,</span> <span class="n">exc</span><span class="o">=</span><span class="n">e</span><span class="p">,</span> <span class="n">max_retries</span><span class="o">=</span><span class="mi">1</span><span class="p">)</span>
</pre></div>


<h4>Explanation</h4>
<p>In our task, we generate a random number between 1 and 10. If the number is even then the task succeeds and returns the sum of numbers. If the generated random number is odd then the task fails, in which case we retry the task after 2 seconds.</p>
<h4>Outputs of some random runs of tasks</h4>
<div class="highlight"><pre><span></span><span class="k">[2015-07-31 17:47:13,800: INFO/MainProcess] Received task: add.add[879c089d-54fb-4592-96e4-325f61bdce39]</span>
<span class="na">[2015-07-31 17:47:13,801: WARNING/Worker-3] 7</span>
<span class="k">[2015-07-31 17:47:13,822: INFO/MainProcess] Received task: add.add[879c089d-54fb-4592-96e4-325f61bdce39] eta:[2015-07-31 12:17:15.811826+00:00]</span>
<span class="na">[2015-07-31 17:47:13,823: INFO/MainProcess] Task add.add[879c089d-54fb-4592-96e4-325f61bdce39] retry: Retry in 2s: Exception()</span>
<span class="na">[2015-07-31 17:47:16,873: WARNING/Worker-1] 8</span>
<span class="na">[2015-07-31 17:47:16,874: INFO/MainProcess] Task add.add[879c089d-54fb-4592-96e4-325f61bdce39] succeeded in 0.00106367497938s: 7</span>
</pre></div>


<p>Generated random number was 7. So task raised an exception and so it was retried in 2 secs. In the retried run, generated random number was 8 which is even and so no exception was raised and instead the sum was calculated and returned.</p>
<p>Another output</p>
<div class="highlight"><pre><span></span><span class="k">[2015-07-31 17:47:33,681: INFO/MainProcess] Received task: add.add[64e43f81-0f80-49ac-a068-4c84c689ea16]</span>
<span class="na">[2015-07-31 17:47:33,681: WARNING/Worker-2] 7</span>
<span class="k">[2015-07-31 17:47:33,703: INFO/MainProcess] Received task: add.add[64e43f81-0f80-49ac-a068-4c84c689ea16] eta:[2015-07-31 12:17:35.692557+00:00]</span>
<span class="na">[2015-07-31 17:47:33,704: INFO/MainProcess] Task add.add[64e43f81-0f80-49ac-a068-4c84c689ea16] retry: Retry in 2s: Exception()</span>
<span class="na">[2015-07-31 17:47:36,890: WARNING/Worker-4] 3</span>
<span class="na">[2015-07-31 17:47:36,894: ERROR/MainProcess] Task add.add[64e43f81-0f80-49ac-a068-4c84c689ea16] raised unexpected: Exception()</span>
<span class="na">Traceback (most recent call last):</span>
  <span class="na">File &quot;/Users/akshar/.virtualenvs/hack/lib/python2.7/site-packages/celery/app/trace.py&quot;, line 240, in trace_task</span>
  <span class="na">...</span>
  <span class="na">File &quot;/Users/akshar/Play/Python/hack/add.py&quot;, line 15, in add</span>
    <span class="na">raise Exception()</span>
<span class="na">Exception</span>
</pre></div>


<p>Generated random number was 7. So task raised an exception and so it was retried in 2 secs. In the retried run, generated random number was 3 which is again odd, so retried task also raised an exception. And since we have set <code>max_retries</code> as 1, no furter retry was done.</p>
<h4>Setting a datetime instead of countdown</h4>
<p>Till now we have been working with <strong>countdown</strong> which tells the number of seconds in which failed task should be retried. We can also set a datetime at which task should be retried.</p>
<p>Let's retry the failed task after 2 seconds but using datetime instead of countdown.</p>
<div class="highlight"><pre><span></span><span class="kn">import</span> <span class="nn">random</span>
<span class="kn">import</span> <span class="nn">datetime</span>
<span class="kn">import</span> <span class="nn">pytz</span>

<span class="kn">from</span> <span class="nn">celery</span> <span class="kn">import</span> <span class="n">Celery</span>

<span class="n">app</span> <span class="o">=</span> <span class="n">Celery</span><span class="p">(</span><span class="s1">&#39;add&#39;</span><span class="p">,</span> <span class="n">broker</span><span class="o">=</span><span class="s1">&#39;redis://localhost:6379/0&#39;</span><span class="p">)</span>

<span class="nd">@app.task</span><span class="p">(</span><span class="n">bind</span><span class="o">=</span><span class="bp">True</span><span class="p">)</span>
<span class="k">def</span> <span class="nf">add</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">x</span><span class="p">,</span> <span class="n">y</span><span class="p">):</span>
    <span class="c1"># Get a random number between 1 and 10</span>
    <span class="n">num</span> <span class="o">=</span> <span class="n">random</span><span class="o">.</span><span class="n">randint</span><span class="p">(</span><span class="mi">1</span><span class="p">,</span> <span class="mi">10</span><span class="p">)</span>
    <span class="k">print</span> <span class="n">num</span>
    <span class="k">try</span><span class="p">:</span>
        <span class="c1"># If number is odd, fail the task</span>
        <span class="k">if</span> <span class="n">num</span> <span class="o">%</span> <span class="mi">2</span><span class="p">:</span>
            <span class="k">raise</span> <span class="ne">Exception</span><span class="p">()</span>
        <span class="c1"># If number is even, succeed the task</span>
        <span class="k">else</span><span class="p">:</span>
            <span class="k">return</span> <span class="n">x</span> <span class="o">+</span> <span class="n">y</span>
    <span class="k">except</span> <span class="ne">Exception</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
        <span class="n">dt</span> <span class="o">=</span> <span class="n">datetime</span><span class="o">.</span><span class="n">datetime</span><span class="o">.</span><span class="n">now</span><span class="p">(</span><span class="n">pytz</span><span class="o">.</span><span class="n">utc</span><span class="p">)</span> <span class="o">+</span> <span class="n">datetime</span><span class="o">.</span><span class="n">timedelta</span><span class="p">(</span><span class="n">seconds</span><span class="o">=</span><span class="mi">1</span><span class="p">)</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">retry</span><span class="p">(</span><span class="n">eta</span><span class="o">=</span><span class="n">dt</span><span class="p">,</span> <span class="n">exc</span><span class="o">=</span><span class="n">e</span><span class="p">,</span> <span class="n">max_retries</span><span class="o">=</span><span class="mi">1</span><span class="p">)</span>
</pre></div>


<p>Output</p>
<div class="highlight"><pre><span></span><span class="k">[2015-07-31 18:59:17,177: INFO/MainProcess] Received task: add.add[b5f95e50-da3a-4295-871a-fc940bef5c46]</span>
<span class="na">[2015-07-31 18:59:17,178: WARNING/Worker-3] 1</span>
<span class="k">[2015-07-31 18:59:17,200: INFO/MainProcess] Received task: add.add[b5f95e50-da3a-4295-871a-fc940bef5c46] eta:[2015-07-31 13:29:19.178833+00:00]</span>
<span class="na">[2015-07-31 18:59:17,202: INFO/MainProcess] Task add.add[b5f95e50-da3a-4295-871a-fc940bef5c46] retry: Retry at 2015-07-31 13:29:19.178833+00:00: Exception()</span>
<span class="na">[2015-07-31 18:59:19,690: WARNING/Worker-1] 10</span>
<span class="na">[2015-07-31 18:59:19,691: INFO/MainProcess] Task add.add[b5f95e50-da3a-4295-871a-fc940bef5c46] succeeded in 0.00107540999306s: 7</span>
</pre></div>


<h3>Retrying failed Twitter tasks</h3>
<p>I assume you have the idea of <a href="https://pypi.python.org/pypi/twitter" target="_blank">Python twitter library.</a>. My code before using retry looked like.</p>
<div class="highlight"><pre><span></span><span class="kn">import</span> <span class="nn">twitter</span>

<span class="nd">@app.task</span><span class="p">(</span><span class="n">bind</span><span class="o">=</span><span class="bp">True</span><span class="p">)</span>
<span class="k">def</span> <span class="nf">fetch_tweets</span><span class="p">(</span><span class="bp">self</span><span class="p">)</span>
    <span class="n">auth</span> <span class="o">=</span> <span class="n">twitter</span><span class="o">.</span><span class="n">OAuth</span><span class="p">(</span><span class="n">oauth_token</span><span class="p">,</span> <span class="n">oauth_token_secret</span><span class="p">,</span> <span class="n">key</span><span class="p">,</span> <span class="n">secret</span><span class="p">)</span>
    <span class="n">client</span> <span class="o">=</span> <span class="n">twitter</span><span class="o">.</span><span class="n">Twitter</span><span class="p">(</span><span class="n">auth</span><span class="o">=</span><span class="n">auth</span><span class="p">)</span>
    <span class="n">params</span> <span class="o">=</span> <span class="p">{</span><span class="s1">&#39;user_id&#39;</span><span class="p">:</span> <span class="n">user_id</span><span class="p">,</span> <span class="s1">&#39;count&#39;</span><span class="p">:</span> <span class="mi">2</span><span class="p">}</span>
    <span class="n">response</span> <span class="o">=</span> <span class="n">client</span><span class="o">.</span><span class="n">favorites</span><span class="o">.</span><span class="n">list</span><span class="p">(</span><span class="o">**</span><span class="n">params</span><span class="p">)</span>
    <span class="k">return</span> <span class="n">response</span>
</pre></div>


<p>Till first 180 calls, tasks were succeeding. 181st call onwards the tasks started failing. So I changed it to.</p>
<div class="highlight"><pre><span></span><span class="kn">import</span> <span class="nn">twitter</span>

<span class="nd">@app.task</span><span class="p">(</span><span class="n">bind</span><span class="o">=</span><span class="bp">True</span><span class="p">)</span>
<span class="k">def</span> <span class="nf">fetch_tweets</span><span class="p">(</span><span class="bp">self</span><span class="p">)</span>
    <span class="n">auth</span> <span class="o">=</span> <span class="n">twitter</span><span class="o">.</span><span class="n">OAuth</span><span class="p">(</span><span class="n">oauth_token</span><span class="p">,</span> <span class="n">oauth_token_secret</span><span class="p">,</span> <span class="n">key</span><span class="p">,</span> <span class="n">secret</span><span class="p">)</span>
    <span class="n">client</span> <span class="o">=</span> <span class="n">twitter</span><span class="o">.</span><span class="n">Twitter</span><span class="p">(</span><span class="n">auth</span><span class="o">=</span><span class="n">auth</span><span class="p">)</span>
    <span class="n">params</span> <span class="o">=</span> <span class="p">{</span><span class="s1">&#39;user_id&#39;</span><span class="p">:</span> <span class="n">user_id</span><span class="p">,</span> <span class="s1">&#39;count&#39;</span><span class="p">:</span> <span class="mi">2</span><span class="p">}</span>
    <span class="k">try</span><span class="p">:</span>
        <span class="n">response</span> <span class="o">=</span> <span class="n">client</span><span class="o">.</span><span class="n">favorites</span><span class="o">.</span><span class="n">list</span><span class="p">(</span><span class="o">**</span><span class="n">params</span><span class="p">)</span>
    <span class="k">except</span> <span class="n">twitter</span><span class="o">.</span><span class="n">TwitterError</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
        <span class="k">if</span> <span class="n">e</span><span class="o">.</span><span class="n">e</span><span class="o">.</span><span class="n">code</span> <span class="o">==</span> <span class="mi">429</span><span class="p">:</span>
            <span class="c1"># 429: rate limit exceeded</span>
            <span class="c1"># Ask Twitter to tell at what time rate limit window gets reset</span>
            <span class="n">rate_limit_status</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">client</span><span class="o">.</span><span class="n">application</span><span class="o">.</span><span class="n">rate_limit_status</span><span class="p">(</span><span class="n">resources</span><span class="o">=</span><span class="s2">&quot;statuses&quot;</span><span class="p">)</span>
            <span class="n">reset</span> <span class="o">=</span> <span class="n">rate_limit_status</span><span class="p">[</span><span class="s2">&quot;resources&quot;</span><span class="p">][</span><span class="s2">&quot;statuses&quot;</span><span class="p">][</span><span class="s2">&quot;/statuses/user_timeline&quot;</span><span class="p">][</span><span class="s2">&quot;reset&quot;</span><span class="p">]</span>
            <span class="n">dt</span> <span class="o">=</span> <span class="n">datetime</span><span class="o">.</span><span class="n">datetime</span><span class="o">.</span><span class="n">utcfromtimestamp</span><span class="p">(</span><span class="n">reset</span><span class="p">)</span>
            <span class="k">raise</span> <span class="bp">self</span><span class="o">.</span><span class="n">retry</span><span class="p">(</span><span class="n">eta</span><span class="o">=</span><span class="n">dt</span><span class="p">,</span> <span class="n">exc</span><span class="o">=</span><span class="n">e</span><span class="p">,</span> <span class="n">max_retries</span><span class="o">=</span><span class="mi">1</span><span class="p">)</span>
    <span class="k">return</span> <span class="n">response</span>
</pre></div>


<p>After this, any failed tasks were retried when Twitter rate limit window gets reset.</p>
            
            
            <hr/>
        </div>
        <section>
        <div class="span2" style="float:right;font-size:0.9em;">
            <h4>Published</h4>
            <time pubdate="pubdate" datetime="2015-08-03T00:23:19+05:30">Aug 3, 2015</time>

<h4>Last Updated</h4>
<time datetime="2015-08-03T10:53:19+05:30">Aug 3, 2015</time>

            <h4>Category</h4>
            <a class="category-link" href="/categories.html#markdown-ref">markdown</a>
            <h4>Tags</h4>
            <ul class="list-of-tags tags-in-article">
                <li><a href="/tags.html#celery-ref">celery
                    <span>1</span>
</a></li>
            </ul>
<h4>Contact</h4>
    <a href="#" title="My You can add links in your config file Profile" class="sidebar-social-links" target="_blank">
    <i class="fa fa-you can add links in your config file sidebar-social-links"></i></a>
    <a href="#" title="My Another social link Profile" class="sidebar-social-links" target="_blank">
    <i class="fa fa-another social link sidebar-social-links"></i></a>
        </div>
        </section>
</div>
</article>
                </div>
                <div class="span1"></div>
            </div>
        </div>
        <div id="push"></div>
    </div>
<footer>
<div id="footer">
    <ul class="footer-content">
        <li class="elegant-power">Powered by <a href="http://getpelican.com/" title="Pelican Home Page">Pelican</a>. Theme: <a href="http://oncrashreboot.com/pelican-elegant" title="Theme Elegant Home Page">Elegant</a> by <a href="http://oncrashreboot.com" title="Talha Mansoor Home Page">Talha Mansoor</a></li>
    </ul>
</div>
</footer>            <script src="http://code.jquery.com/jquery.min.js"></script>
        <script src="//netdna.bootstrapcdn.com/twitter-bootstrap/2.3.2/js/bootstrap.min.js"></script>
        <script>
            function validateForm(query)
            {
                return (query.length > 0);
            }
        </script>

    
    </body>
    <!-- Theme: Elegant built for Pelican
    License : http://oncrashreboot.com/pelican-elegant -->
</html>